#' Generate circos plots from overlap data output
#'
#' @param datatable The GRanges datatable generated by overlap function
#' @param plot.subset Allows for plotting interactions with Hi-C scores only
#' @param display.legend Adds legend to circos plot
#' @param rna.legend Title for RNA legend
#' @param hic.legend Title for Hi-C legend
#' @param circos.color Passes colors to chord diagram for each group
#' @importFrom circlize chordDiagram circos.clear circos.rect
#' circos.trackPlotRegion colorRamp2 circos.par get.cell.meta.data
#' circos.text
#' @importFrom dplyr left_join
#' @importFrom stats setNames aggregate
#' @import graphics
#' @import grDevices
#' @export

circleplot <- function(datatable,
                       plot.subset = FALSE,
                       display.legend = TRUE,
                       hic.legend = "Hi-C Score",
                       hic.range = c(0, 130),
                       rna.legend = "logFPKM",
                       rna.range = c(0, 3.2),
                       circos.color = NULL,
                       ...) {

  finaltable <- (table(datatable$mark1, datatable$mark2))

  #Data frame for circos plot
  circosR <- data.frame(finaltable)
  circosR <- setNames(circosR, c("mark1", "mark2", "Freq"))

  #Compute average scores for each group of interactions
  scoretable <- aggregate(HiCscore~mark1 + mark2, data = datatable, FUN = mean)
  colnames(scoretable)[3] <- "Avg.Score"

  #Generate table for Heatmap
  circosR$mark1 <- as.character(circosR$mark1)
  circosR$mark2 <- as.character(circosR$mark2)
  heatmap <- left_join(circosR, scoretable, by = c("mark1", "mark2"))

  if (plot.subset == "hicscore") {
  circos.clear()
  par(pty="s")
  circos.par(points.overflow.warning=FALSE,
             track.margin = c(0, 0))

  chordDiagram(circosR,
               circos.par(track.margin = c(0, 0)),
               grid.col = circos.color,
               annotationTrack = "grid",
               preAllocateTracks = 2,
               ...)

  circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
    xlim = get.cell.meta.data("xlim")
    ylim = get.cell.meta.data("ylim")
    sector.name = get.cell.meta.data("sector.index")
    circos.text(mean(xlim), ylim[1],
                sector.name,
                facing = "clockwise",
                niceFacing = TRUE,
                adj = c(0.3, 0.3),
                cex = 0.8)
  }
  , bg.border = NA)
  #Add heatmap to chord diagram
  col_fun = colorRamp2(hic.range,
                       c("white", "red"))

  tab1 <- heatmap[order(heatmap$mark1,rev(heatmap$mark2)),]
  tab1[is.na(tab1)] <- 0
  tab2 <- heatmap[order(heatmap$mark2,rev(heatmap$mark1)),]
  tab2[is.na(tab2)] <- 0

  circos.trackPlotRegion(ylim = c(0, 3),
                         circos.par("track.height" = 0.01),
                         bg.border = NA,
                         track.index = 2,
                         panel.fun = function(x, y) {
                           end <- 0
                           sector = get.cell.meta.data("sector.index")
                           aux.tab1 <- tab1[tab1$mark1 == sector,]
                           aux.tab2 <- tab2[tab2$mark2 == sector,]
                           col_tab1 = col_fun(aux.tab1$Avg.Score)
                           col_tab2 = col_fun(aux.tab2$Avg.Score)
                           for(i in 1:nrow(aux.tab1)){
                             start <- end
                             end <- end + aux.tab1[i,"Freq"]
                             circos.rect(start, 0, end, 2,
                                         border = col_tab1[i],
                                         col = col_tab1[i],
                                         sector.index = sector,
                                         track.index = 2)
                           }
                           for(i in 1:nrow(aux.tab2)){
                             start <- end
                             end <- end + aux.tab2[i,"Freq"]
                             circos.rect(start, 0, end, 2,
                                         border = col_tab2[i],
                                         col = col_tab2[i],
                                         sector.index = sector,
                                         track.index = 2)
                           }
                           end <- 0
                         })
  }
  else {
  #Draw chord diagram
  FPKM1score <- aggregate(logFPKM1~mark1 + mark2, data = datatable, FUN = mean)
  FPKM2score <- aggregate(logFPKM2~mark1 + mark2, data = datatable, FUN = mean)
  heatmap <- left_join(heatmap, FPKM1score, by = c("mark1", "mark2"))
  heatmap <- left_join(heatmap, FPKM2score, by = c("mark1", "mark2"))
  circos.clear()
  par(pty="s")
  circos.par(points.overflow.warning=FALSE,
             track.margin = c(0, 0))

  chordDiagram(circosR,
               circos.par(track.margin = c(0, 0)),
               grid.col = circos.color,
               annotationTrack = "grid",
               preAllocateTracks = 3,
               ...)

  circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
    xlim = get.cell.meta.data("xlim")
    ylim = get.cell.meta.data("ylim")
    sector.name = get.cell.meta.data("sector.index")
    circos.text(mean(xlim), ylim[1],
                sector.name,
                facing = "clockwise",
                niceFacing = TRUE,
                adj = c(0.3, 0.3),
                cex = 0.8)
    }
    , bg.border = NA)
  #Add heatmap to chord diagram
  col_fun = colorRamp2(hic.range,
                       c("white", "red"))

  tab1 <- heatmap[order(heatmap$mark1,rev(heatmap$mark2)),]
  tab1[is.na(tab1)] <- 0
  tab2 <- heatmap[order(heatmap$mark2,rev(heatmap$mark1)),]
  tab2[is.na(tab2)] <- 0

  circos.trackPlotRegion(ylim = c(0, 3),
                         circos.par("track.height" = 0.01),
                         bg.border = NA,
                         track.index = 3,
                         panel.fun = function(x, y) {
                           end <- 0
                           sector = get.cell.meta.data("sector.index")
                           aux.tab1 <- tab1[tab1$mark1 == sector,]
                           aux.tab2 <- tab2[tab2$mark2 == sector,]
                           col_tab1 = col_fun(aux.tab1$Avg.Score)
                           col_tab2 = col_fun(aux.tab2$Avg.Score)
                           for(i in 1:nrow(aux.tab1)){
                             start <- end
                             end <- end + aux.tab1[i,"Freq"]
                             circos.rect(start, -0.3, end, 2,
                                         border = col_tab1[i],
                                         col = col_tab1[i],
                                         sector.index = sector,
                                         track.index = 3)
                           }
                           for(i in 1:nrow(aux.tab2)){
                             start <- end
                             end <- end + aux.tab2[i,"Freq"]
                             circos.rect(start, -0.3, end, 2,
                                         border = col_tab2[i],
                                         col = col_tab2[i],
                                         sector.index = sector,
                                         track.index = 3)
                           }
                           end <- 0
                         })

  col_fun2 = colorRamp2(rna.range,
                        c("white", "black"))

  circos.trackPlotRegion(ylim = c(0, 3),
                         circos.par("track.height" = 0.01),
                         bg.border = NA,
                         track.index = 2,
                         panel.fun = function(x, y) {
                           end <- 0
                           sector = get.cell.meta.data("sector.index")
                           aux.tab1 <- tab1[tab1$mark1 == sector,]
                           aux.tab2 <- tab2[tab2$mark2 == sector,]
                           col_tab1 = col_fun2(aux.tab1$logFPKM1)
                           col_tab2 = col_fun2(aux.tab2$logFPKM2)
                           for(i in 1:nrow(aux.tab1)){
                             start <- end
                             end <- end + aux.tab1[i,"Freq"]
                             circos.rect(start, -1.2, end, 1.5,
                                         border = col_tab1[i],
                                         col = col_tab1[i],
                                         sector.index = sector,
                                         track.index = 2)
                           }
                           for(i in 1:nrow(aux.tab2)){
                             start <- end
                             end <- end + aux.tab2[i,"Freq"]
                             circos.rect(start, -1.2, end, 1.5,
                                         border = col_tab2[i],
                                         col = col_tab2[i],
                                         sector.index = sector,
                                         track.index = 2)
                           }
                           end <- 0
                         })
  }

  if (display.legend == TRUE & plot.subset == FALSE) {
  legend("bottomleft", title = rna.legend,
         legend = c(min(rna.range),
                    (min(rna.range)+max(rna.range))/2,
                    max(rna.range)),
         fill=colorRampPalette(c("white", "black"))(3))
  legend("bottomright", title = hic.legend,
         legend = c(min(hic.range),
                    (min(hic.range)+max(hic.range))/2,
                    max(hic.range)),
         fill=colorRampPalette(c("white", "red"))(3))
  }
  if (display.legend == "RNA") {
    legend("bottomleft", title = rna.legend,
           legend = c(min(rna.range),
                      (min(rna.range)+max(rna.range))/2,
                      max(rna.range)),
           fill=colorRampPalette(c("white", "black"))(3))
  }
  if (display.legend == "HIC" | plot.subset == "hicscore") {
    legend("bottomright", title = hic.legend,
           legend = c(min(hic.range),
                      (min(hic.range)+max(hic.range))/2,
                      max(hic.range)),
           fill=colorRampPalette(c("white", "red"))(3))
  }

}
